apiVersion: org.kie.trustyai/v1alpha1
kind: TrustyAIService
metadata:
  name: trustyai-service-test
spec:
  image: "quay.io/trustyai/trustyai-service:0.1.0"
  storage:
    format: "PVC"
    folder: "/inputs"
  data:
    filename: "data.csv"
    format: "CSV"
  metrics:
    schedule: "5s"

